# Generated by Django 2.2 on 2020-04-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_img', models.ImageField(upload_to='content1/')),
                ('style_img', models.ImageField(upload_to='style1/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
