# Generated by Django 2.2 on 2020-04-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_auto_20200421_0551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
